spring:
  application:
    name: hackathon-auth-ms

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:q3s6v9y$B&E)H@McQfTjWnZr4u7x!A%C}
  expiration: ${JWT_EXPIRATION:3600000}
  issuer: ${JWT_ISSUER:hackathon-issuer}

server:
  port: ${APP_PORT:8080}
